services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: spacetruckers
      POSTGRES_USER: spacetruckers
      POSTGRES_PASSWORD: spacetruckers
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  api:
    build:
      context: .
      dockerfile: src/SpaceTruckers.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      FeatureManagement__UseDomainPersistentStorage: "true"
      ConnectionStrings__SpaceTruckersDb: "Host=db;Port=5432;Database=spacetruckers;Username=spacetruckers;Password=spacetruckers"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
